Đồ án cuối kỳ/Web/Web/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class Picture
    {
        public int Id { get; set; }
        public String PictureName { get; set; }
        [DataType(DataType.ImageUrl)]
        public string PictureUrl { get; set; }
        public int Favourites { get; set; } //số lượt thích bức ảnh
        public int Downloads { get; set; } // số lượt download bức ảnh
        public double TotalRates { get; set; }// điểm tổng đánh giá ảnh
        public DateTime DateUploaded { get; set; }

        public int UserProfileUserId { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Resolution> Resolutions { get; set; }
        public virtual ICollection<Rate> Rates { get; set; }
    }
}

Đồ án cuối kỳ/Web/Web/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class CommentController : Controller
    {
        private WebDbContext db = new WebDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Picture).Include(c => c.UserProfile);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "PictureName");
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment, int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.DateCreated = DateTime.Now;
                comment.PictureId = idpost;
                comment.UserProfileUserId = db.UserProfiles.Select(s => new { s.UserId, s.UserName })
                    .Where(d => d.UserName == User.Identity.Name).Single().UserId;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("viewComment", comment);
                //return RedirectToAction("Index");
            }

            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "PictureName", comment.PictureId);
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", comment.UserProfileUserId);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "PictureName", comment.PictureId);
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", comment.UserProfileUserId);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "PictureName", comment.PictureId);
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", comment.UserProfileUserId);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Đồ án cuối kỳ/Web/Web/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    [Authorize]
    public class PictureController : Controller
    {
        private WebDbContext db = new WebDbContext();

        //
        // GET: /Picture/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var pictures = db.Pictures.Include(p => p.UserProfile);
            return View(pictures.ToList());
        }

        //
        // GET: /Picture/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Picture picture = db.Pictures.Find(id);
            ViewData["idpost"] = id;
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        public ActionResult PictureLinkTag(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            return View(tag);
        }

        public ActionResult PictureLinkCategory(int id = 0)
        {
            Category category = db.Categories.Find(id);
            return View(category);
        }
        //
        // GET: /Picture/Create

        public ActionResult Create(Category ca)
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Picture/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Picture picture, HttpPostedFileBase file, String TagName, String CategoryName)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/")
                                                          + file.FileName);
                    picture.PictureUrl = file.FileName;
                    picture.UserProfileUserId = db.UserProfiles.Select(s => new { s.UserId, s.UserName })
                    .Where(d => d.UserName == User.Identity.Name).Single().UserId;
                    picture.DateUploaded = DateTime.Now;

                    // tao list cac tag
                    List<Tag> Tags = new List<Tag>();
                    // tach cac tag theo dau ,
                    string[] TagNames = TagName.Split(',');
                    // lap cac tag vua tach
                    foreach (string item in TagNames)
                    {
                        // tim xem tag comtem da co hay chua
                        Tag tagExits = null;
                        var listTag = db.Tags.Where(y => y.TagName.Equals(item));
                        if (listTag.Count() > 0)
                        {
                            // neu co tag roi thi add them post vao
                            tagExits = listTag.First();
                            tagExits.Pictures.Add(picture);

                        }
                        else
                        {
                            // neu chua thi tao tag moi
                            tagExits = new Tag();
                            tagExits.TagName = item;
                            tagExits.Pictures = new List<Picture>();
                            tagExits.Pictures.Add(picture);
                        }
                        //add vao list cac tag
                        Tags.Add(tagExits);
                    }
                    // gan lis tag cho post
                    picture.Tags = Tags;


                    //// tao list cac category
                    //List<Category> Categories = new List<Category>();
                    //// tach cac category theo dau ,
                    //string[] CategoryNames = CategoryName.Split(',');
                    //// lap cac category vua tach
                    //foreach (string item in CategoryNames)
                    //{
                    //    // tim xem category da co hay chua
                    //    Category categoryExits = null;
                    //    var listCategory = db.Categories.Where(y => y.CategoryName.Equals(item));
                    //    if (listCategory.Count() > 0)
                    //    {
                    //        // neu co Categories roi thi add them post vao
                    //        categoryExits = listCategory.First();
                    //        categoryExits.Pictures.Add(picture);

                    //    }
                    //    else
                    //    {
                    //        // neu chua thi tao Categories moi
                    //        categoryExits = new Category();
                    //        categoryExits.CategoryName = item;
                    //        categoryExits.Pictures = new List<Picture>();
                    //        categoryExits.Pictures.Add(picture);
                    //    }
                    //    //add vao list cac Categories
                    //    Categories.Add(categoryExits);
                    //}
                    //// gan lis Categories cho post
                    //picture.Categories = Categories;
                
                }
                
                db.Pictures.Add(picture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", picture.UserProfileUserId);
            return View(picture);
        }

        //
        // GET: /Picture/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    Picture picture = db.Pictures.Find(id);
        //    if (picture == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", picture.UserProfileUserId);
        //    return View(picture);
        //}

        ////
        //// POST: /Picture/Edit/5

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(Picture picture)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(picture).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", picture.UserProfileUserId);
        //    return View(picture);
        //}

        //
        // GET: /Picture/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        //
        // POST: /Picture/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picture picture = db.Pictures.Find(id);
            db.Pictures.Remove(picture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Đồ án cuối kỳ/Web/Web/Views/Picture/Create.cshtml
@model Web.Models.Picture

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Picture", null, FormMethod.Post,
                              new { enctype = "multipart/form-data" })){
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend style="color:white">Picture</legend>

        <div class="form-group">
            @Html.Label("Picture Name", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PictureName, new { @class = "form-control", @placeholder = "Enter Picture Name" })
                @Html.ValidationMessageFor(model => model.PictureName)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Write tags", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => new Web.Models.Tag().TagName, new { @class = "form-control", @placeholder = "Enter tags" })
                @Html.ValidationMessageFor(model => new Web.Models.Tag().TagName)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Choose categories", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => new Web.Models.Category().CategoryName, new { @class = "form-control", @placeholder = "Enter categories" })
                @Html.ValidationMessageFor(model => new Web.Models.Category().CategoryName)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Choose Picture", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <input id="PictureUrl" title="Upload a product image"
                       type="file" name="file" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-info" value="Start Upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a class="btn btn-warning" href="~/Picture">Cancel</a>
            </div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Đồ án cuối kỳ/Web/Web/Views/Picture/Delete.cshtml
@model Web.Models.Picture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Picture</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PictureName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PictureName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PictureUrl)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PictureUrl)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Favourites)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Favourites)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Downloads)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Downloads)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TotalRates)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TotalRates)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateUploaded)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateUploaded)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Đồ án cuối kỳ/Web/Web/Views/Picture/Details.cshtml
@model Web.Models.Picture

@{
    ViewBag.Title = "Details";
}

<h2>Picture Detail</h2>

<fieldset>
    @*<legend>Picture</legend>*@
    <div class="display-field">
        Picture Name: @Html.DisplayFor(model => model.PictureName)
    </div>
    <div class="display-field">
        User: @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        Date Uploaded: @Html.DisplayFor(model => model.DateUploaded)
    </div>
    <div class="display-field">
        Favourites: @Html.DisplayFor(model => model.Favourites)
    </div>

    <div class="display-field">
        Downloads: @Html.DisplayFor(model => model.Downloads)
    </div>

    <div class="display-field">
        TotalRates: @Html.DisplayFor(model => model.TotalRates)
    </div>

</fieldset>
<fieldset>
    <h4 style="color:white">Categories</h4>
    @foreach (var c in Model.Categories)
    {
        @Html.ActionLink(c.CategoryName, "PictureLinkCategory/" + c.CategoryId, "Picture")
    }
</fieldset>
<fieldset>
    <h4 style="color:white">Tags:</h4>
    @foreach (var t in Model.Tags)
    {
        @Html.ActionLink(t.TagName, "PictureLinkTag/" + t.TagId, "Picture")
    }
</fieldset>
<br>
<fieldset>
    <img src="~/Images/@Model.PictureUrl" width="1150" height="700" />
</fieldset>
@Html.Partial("_addComment", new Web.Models.Comment(), ViewData)

<fieldset>
    <legend style="color:white">Comments</legend>
    <div id="result">
        @foreach (var c in Model.Comments.OrderByDescending(s => s.DateCreated).Take(10))
        {
            <div class="display-field">
                Post in: @Html.DisplayFor(s => c.DateCreated)
            </div>
            <div class="display-field">
                @Html.DisplayFor(s => c.UserProfile.UserName)
            </div>
            <div class="display-field">
                @Html.DisplayFor(s => c.Content)
            </div>
        }
    </div>
</fieldset>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

Đồ án cuối kỳ/Web/Web/Views/Picture/Index.cshtml
@model IEnumerable<Web.Models.Picture>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <h2>Pictures</h2>

    <p>
        <a class="btn btn-lg btn-primary" title="Create New" href="@Url.Action("Create","Picture")">Upload Pictures</a>
    </p>
    <table>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @*<a class="btn btn-sm btn-default" title="Details" href="@Url.Action("Details", "Picture", new { id = item.Id })">Detail</a>*@
                    <a class="btn btn-sm btn-default" title="Delete" href="@Url.Action("Delete", "Picture", new { id = item.Id })">Delete</a>
                    <br />
                    <a href="@Url.Action("Details", "Picture", new { id = item.Id })">
                        <img src="~/Images/@item.PictureUrl" width="720" height="400" />
                    </a>
                    <br />
                    <br />
                </td>

            </tr>
        }
    </table>
</div>

Đồ án cuối kỳ/Web/Web/Views/Picture/PictureLinkCategory.cshtml
@model Web.Models.Category

@{
    ViewBag.Title = "Picture-Category";
}

<div class="container">
    <h2>Pictures</h2>
    <table>
        @foreach (var item in Model.Pictures)
        {
            <tr>
                <td>
                    <a class="btn btn-sm btn-default" title="Details" href="@Url.Action("Details", "Picture", new { id = item.Id })">Detail</a>
                    <a class="btn btn-sm btn-default" title="Delete" href="@Url.Action("Delete", "Picture", new { id = item.Id })">Delete</a>
                    <br />
                    <img src="~/Images/@item.PictureUrl" width="720" height="400" />
                    <br />
                    <br />
                </td>

            </tr>
        }
    </table>
</div>

Đồ án cuối kỳ/Web/Web/Views/Picture/PictureLinkTag.cshtml
@model Web.Models.Tag

@{
    ViewBag.Title = "Picture-Tag";
}

<div class="container">
    <h2>Pictures</h2>
    <table>
        @foreach (var item in Model.Pictures)
        {
            <tr>
                <td>
                    <a class="btn btn-sm btn-default" title="Details" href="@Url.Action("Details", "Picture", new { id = item.Id })">Detail</a>
                    <a class="btn btn-sm btn-default" title="Delete" href="@Url.Action("Delete", "Picture", new { id = item.Id })">Delete</a>
                    <br />
                    <img src="~/Images/@item.PictureUrl" width="720" height="400" />
                    <br />
                    <br />
                </td>

            </tr>
        }
    </table>
</div>

Đồ án cuối kỳ/Web/Web/Views/Picture/_addComment.cshtml
@model Web.Models.Comment

@using (Html.BeginForm("Create", "Comment", FormMethod.Post, new { id = "my-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend style="color:white">All Comment</legend>

        @*<div class="form-group">*@
            <div class="col-lg-10">
                @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @placeholder = "Write your comment" })
                @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
            </div>
        @*</div>*@
        @Html.Hidden("idpost", ViewData["idpost"])
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </fieldset>
}

<script src="~/Scripts/addComment.js"></script>