Đồ án cuối kỳ/Web/Web/Models/ResolutionGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class ResolutionGroup
    {
        //nhóm kích thước ảnh
        public int Id { get; set; }
        public String ResolutionGroupName { get; set; }

        public virtual ICollection<Resolution> Resolutions { get; set; }
    }
}

Đồ án cuối kỳ/Web/Web/Controllers/ResolutionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class ResolutionController : Controller
    {
        private WebDbContext db = new WebDbContext();

        //
        // GET: /Resolution/

        public ActionResult Index()
        {
            var resolutions = db.Resolutions.Include(r => r.ResolutionGroup);
            return View(resolutions.ToList());
        }

        //
        // GET: /Resolution/Details/5

        public ActionResult Details(int id = 0)
        {
            Resolution resolution = db.Resolutions.Find(id);
            if (resolution == null)
            {
                return HttpNotFound();
            }
            return View(resolution);
        }

        //
        // GET: /Resolution/Create

        public ActionResult Create()
        {
            ViewBag.ResolutionGroupId = new SelectList(db.ResolutionGroups, "Id", "ResolutionGroupName");
            return View();
        }

        //
        // POST: /Resolution/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Resolution resolution)
        {
            if (ModelState.IsValid)
            {
                db.Resolutions.Add(resolution);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ResolutionGroupId = new SelectList(db.ResolutionGroups, "Id", "ResolutionGroupName", resolution.ResolutionGroupId);
            return View(resolution);
        }

        //
        // GET: /Resolution/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Resolution resolution = db.Resolutions.Find(id);
            if (resolution == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResolutionGroupId = new SelectList(db.ResolutionGroups, "Id", "ResolutionGroupName", resolution.ResolutionGroupId);
            return View(resolution);
        }

        //
        // POST: /Resolution/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Resolution resolution)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resolution).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ResolutionGroupId = new SelectList(db.ResolutionGroups, "Id", "ResolutionGroupName", resolution.ResolutionGroupId);
            return View(resolution);
        }

        //
        // GET: /Resolution/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Resolution resolution = db.Resolutions.Find(id);
            if (resolution == null)
            {
                return HttpNotFound();
            }
            return View(resolution);
        }

        //
        // POST: /Resolution/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Resolution resolution = db.Resolutions.Find(id);
            db.Resolutions.Remove(resolution);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Đồ án cuối kỳ/Web/Web/Controllers/ResolutionGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class ResolutionGroupController : Controller
    {
        private WebDbContext db = new WebDbContext();

        //
        // GET: /ResolutionGroup/

        public ActionResult Index()
        {
            return View(db.ResolutionGroups.ToList());
        }

        //
        // GET: /ResolutionGroup/Details/5

        public ActionResult Details(int id = 0)
        {
            ResolutionGroup resolutiongroup = db.ResolutionGroups.Find(id);
            if (resolutiongroup == null)
            {
                return HttpNotFound();
            }
            return View(resolutiongroup);
        }

        //
        // GET: /ResolutionGroup/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ResolutionGroup/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ResolutionGroup resolutiongroup)
        {
            if (ModelState.IsValid)
            {
                db.ResolutionGroups.Add(resolutiongroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(resolutiongroup);
        }

        //
        // GET: /ResolutionGroup/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ResolutionGroup resolutiongroup = db.ResolutionGroups.Find(id);
            if (resolutiongroup == null)
            {
                return HttpNotFound();
            }
            return View(resolutiongroup);
        }

        //
        // POST: /ResolutionGroup/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ResolutionGroup resolutiongroup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resolutiongroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(resolutiongroup);
        }

        //
        // GET: /ResolutionGroup/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ResolutionGroup resolutiongroup = db.ResolutionGroups.Find(id);
            if (resolutiongroup == null)
            {
                return HttpNotFound();
            }
            return View(resolutiongroup);
        }

        //
        // POST: /ResolutionGroup/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ResolutionGroup resolutiongroup = db.ResolutionGroups.Find(id);
            db.ResolutionGroups.Remove(resolutiongroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Đồ án cuối kỳ/Web/Web/Views/ResolutionGroup/Create.cshtml
@model Web.Models.ResolutionGroup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend style="color:white">Resolutions</legend>

        <div class="form-group">
            @Html.Label("Resolution Group", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ResolutionGroupName, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResolutionGroupName)
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-info" value="Create" />
            </div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Đồ án cuối kỳ/Web/Web/Views/ResolutionGroup/Delete.cshtml
@model Web.Models.ResolutionGroup

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ResolutionGroup</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ResolutionGroupName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ResolutionGroupName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Đồ án cuối kỳ/Web/Web/Views/ResolutionGroup/Details.cshtml
@model Web.Models.ResolutionGroup

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ResolutionGroup</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ResolutionGroupName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ResolutionGroupName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Đồ án cuối kỳ/Web/Web/Views/ResolutionGroup/Edit.cshtml
@model Web.Models.ResolutionGroup

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ResolutionGroup</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.ResolutionGroupName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ResolutionGroupName)
            @Html.ValidationMessageFor(model => model.ResolutionGroupName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Đồ án cuối kỳ/Web/Web/Views/ResolutionGroup/Index.cshtml
@model IEnumerable<Web.Models.ResolutionGroup>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="masthead">
        <br />
        <ul class="nav nav-justified" style="opacity:0.78; border-radius:10px">
            <li>@Html.ActionLink("High definition", "Index", "Resolution", null, new { @class = "active" })</li>
            <li>@Html.ActionLink("Widescreen", "Index", "ResolutionGroup")</li>
            <li>@Html.ActionLink("Normal", "Index", "ResolutionGroup")</li>
            <li>@Html.ActionLink("Other", "Index", "ResolutionGroup")</li>
        </ul>
    </div>
</div>